### ISSUE TITLE
Add support for read-only mode (mirrored request)

### ISSUE THREAD

**Issue by mizvyt** [prashnts/pybloomfiltermmap3#12]
This original comes from here:
https://github.com/axiak/pybloomfiltermmap/pull/59

Also added here:
https://github.com/axiak/pybloomfiltermmap/pull/83

Since the original repository seems to be dead, it would be nice to see some updates here.

**Comment by mizvyt** [comment]
Addressed in https://github.com/prashnts/pybloomfiltermmap3/pull/13

**Comment by prashnts** [comment]
Thanks! I've reviewed them and after you've seen them we can prepare a release.

Since this is not really a bugfix patch, let's bump next release to `v0.5.0`?

**Comment by mizvyt** [comment]
> Since this is not really a bugfix patch, let's bump next release to `v0.5.0`?

Sounds good! We could add a milestone and include the pending PRs with this tag.

**Comment by prashnts** [comment]
Great, would you mind resolving merge conflict in #13? I'll upload the package to pypi by evening tomorrow.

In summary: `v0.5.0` would include #11, #13 and #14. Nice! :D

**Comment by prashnts** [comment]
Closed via b903066f17ab3173426b56a53325ebd86ac9891c

v0.5.0 is up on PyPI.
