### ISSUE TITLE
BloomFilter().name returns encoded string

### ISSUE THREAD

**Issue by mizvyt** [prashnts/pybloomfiltermmap3#16]
I'd normally expect a string instance, instead I get bytes.
My suggestion is to leave this as it is, but issue a `DeprecationWarning` in the `0.5.0` release, for the next minor version (`0.6.0` or smth).

Would `BloomFilter().filename` make more sense? Then no breaking changes would need to be made until then.

**Comment by prashnts** [comment]
> I'd normally expect a string instance, instead I get bytes.

I'd expect the same. `.filename` sounds good -- sorta a middle ground between breaking changes vs. api improvement.

**Comment by mizvyt** [comment]
[0.5.2](https://pypi.org/project/pybloomfiltermmap3/0.5.2/) is out with the fix.
