### ISSUE TITLE
Can we include bit array as a property of Bloom Filter?

### ISSUE THREAD

**Issue by AaronRanAn** [prashnts/pybloomfiltermmap3#19]
Most the original python Bloom Filter implementation includes the bit vector representation as a property, as in `BloomFilter.bitarray`. This has two major benefits:

1) Further bit-wise application can be easily carried out, such as cardinality estimation for union, inspection of Bloom Filters, flipping Bloom Filter bit with a small probability. 
2) Easily debug and explain to people how Bloom Filter looks and works. 

Can we add bit vector/array as a property for pybloomfiltermmap3's Bloom Filter as well? Since pybloomfiltermmap3 has become one of the most modern and scalable python BF implementation. 

Thanks for considering! 

cc. @mizvyt for discussion in axiak/pybloomfiltermmap.

**Comment by mizvyt** [comment]
I've created a PR for this. See my comments there also.

**Comment by mizvyt** [comment]
[0.5.2](https://pypi.org/project/pybloomfiltermmap3/0.5.2/) is out with the feature.
