### ISSUE TITLE
PyPI Release

### ISSUE THREAD

**Issue by prashnts** [prashnts/pybloomfiltermmap3#2]
@endrebak This build is passing the unittests and is fit to be put on PyPI.

_Travis_: https://travis-ci.org/PrashntS/pybloomfiltermmap3/builds/121792173

**Comment by prashnts** [comment]
Closed in 89ecafdf3bd135fddfd8ca52d977be731dec120d 

The PyPI version is installed via: `pip install pybloomfiltermmap3`

**Comment by endrebak** [comment]
Thanks. Now I can install the appropriate version using an if python2 or python3 in the setup.py script.

**Comment by prashnts** [comment]
Yes, though, you can also have an exception handle here. I have added a `SystemError` exception which is triggered if you try to install in Python versions below 3, just to be safe. Though, Ideally I _would_ want that this could be merged to the primary repo.
