### ISSUE TITLE
ImportError: Error relocating  fmix64: symbol not found

### ISSUE THREAD

**Issue by lbeeon** [prashnts/pybloomfiltermmap3#32]
I try to run pybloomfiltermmap3 in dind(18.09.7-dind). The install process looks fine, but when I trying to import the module get the error message.
```
Python 3.8.2 (default, Feb 29 2020, 17:03:31)
[GCC 9.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>
>>> from pybloomfilter import BloomFilter
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: Error relocating /usr/lib/python3.8/site-packages/pybloomfiltermmap3-0.5.2-py3.8-linux-x86_64.egg/pybloomfilter.cpython-38-x86_64-linux-gnu.so: fmix64: symbol not found
```

I try to build from source, got the same result.
I try to remove the `FORCE_INLINE` in `MurmurHash3.c` and reinstall then it works.
Any better way to solving this?

**Comment by mizvyt** [comment]
@prashnts have a look at this?

**Comment by mizvyt** [comment]
@lbeeon could you check if this solves your issue? https://github.com/prashnts/pybloomfiltermmap3/pull/33

**Comment by mizvyt** [comment]
I managed to replicate this issue using the same image (docker:18.09.7-dind) and Python 3.7.7. #33 seems to address it. Closing.
