### ISSUE TITLE
Setup a github action workflow

### ISSUE THREAD

**Issue by prashnts** [prashnts/pybloomfiltermmap3#39]
@mizvyt so the github actions are not running (I can't even find a button to "trigger" it). 

I had a look [here][1] and [here][2] (from another project where it does work), but didn't have much time to review them all, so I just made a release manually to get v0.5.3 out.

Honestly, if it seems too complicated, I'd rather revert my commits and I'd take care of publishing new ones manually. Reminds me of https://xkcd.com/1319/ =D

Btw, thanks for making changelog better formatted, and I quite like the readme ;)
Should we perhaps switch the docs theme to something newer too? (current one is sorta broken on ipads).

[1]: https://github.com/actions/starter-workflows/blob/master/ci/python-package.yml
[2]: https://github.com/CyberCRI/learn-ext/blob/master/.github/workflows/nodejs.yml

**Comment by prashnts** [comment]
Interesting...

<img width="638" alt="Screenshot 2020-08-22 at 01 50 27" src="https://user-images.githubusercontent.com/5663391/90943338-db226080-e419-11ea-8646-b4b9db0afbd6.png">

**Comment by prashnts** [comment]
honestly, looks like it's easier to just revert this. i'll make it in a separate commit instead.

**Comment by mizvyt** [comment]
yeah, no worries.
as for the docs, do you know if there are any specific mobile friendly templates available?

**Comment by prashnts** [comment]
cool! i'll set one up (hopefully it should just work with whatever we have right now) and make a pr
