### ISSUE TITLE
New update??? Not possible create 1billion bloom...

### ISSUE THREAD

**Issue by pianistprogram** [prashnts/pybloomfiltermmap3#45]
Is it possible to release a new update with the ability to save the Bloom filter from RAM to the hard disk, with the ability to combine different filters into one? I can't create a filter with 1 billion records! And in conclusion, thank you for your efforts!

**Comment by prashnts** [comment]
Currrently it is not possible to persist the filter that's initialised in memory to disk.

However you might have luck with using Base64 serialization in that case.

For 1 billion records you probably need to check the accuracy parameters, as well as limits on the hashes  (which is internal).
