### ISSUE TITLE
macos install error on python3.6.8 vs pybloomfiltermmap3>=0.5.6

### ISSUE THREAD

**Issue by Daletxt** [prashnts/pybloomfiltermmap3#53]
Environment:
macOS Monterey 12.6.5
python3.6.8
"python install pybloomfiltermmap3==0.5.5" is OK

python install pybloomfiltermmap3==0.5.6

  ERROR: Command errored out with exit status 1:
   command: '/Users/Shared/.../venv/bin/python' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/13/9zyvvwg513z6vggfnq5zq8fr0000gp/T/pip-install-3qeea8de/pybloomfiltermmap3_1d33fa129eb44e14ac5d70679a7a44ba/setup.py'"'"'; __file__='"'"'/private/var/folders/13/9zyvvwg513z6vggfnq5zq8fr0000gp/T/pip-install-3qeea8de/pybloomfiltermmap3_1d33fa129eb44e14ac5d70679a7a44ba/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/13/9zyvvwg513z6vggfnq5zq8fr0000gp/T/pip-wheel-lgpz1bvh
       cwd: /private/var/folders/13/9zyvvwg513z6vggfnq5zq8fr0000gp/T/pip-install-3qeea8de/pybloomfiltermmap3_1d33fa129eb44e14ac5d70679a7a44ba/
  Complete output (10 lines):
  running bdist_wheel
  running build
  running build_ext
  building 'pybloomfilter' extension
  creating build
  creating build/temp.macosx-10.14-x86_64-3.6
  creating build/temp.macosx-10.14-x86_64-3.6/src
  clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -I/Users/Shared/Relocated Items/Security/mac/project/webcrawler/venv/include -I/Users/socar/.pyenv/versions/3.6.8/include/python3.6m -c src/mmapbitarray.c -o build/temp.macosx-10.14-x86_64-3.6/src/mmapbitarray.o
  xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
  error: command 'clang' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for pybloomfiltermmap3

**Comment by prashnts** [comment]
This looks like an issue with your env. -- You normally need xcode command line tools to compile on Mac.
