### ISSUE TITLE
 Building wheel for pybloomfiltermmap3 (pyproject.toml) did not run successfully

### ISSUE THREAD

**Issue by rehan43v3r** [prashnts/pybloomfiltermmap3#54]
Unable to install pybloomfiltermmap3 windows 11, python 3.12 and pip3 failed... can you please implement an alternative solution for this fix....

![pybloomfiltermap building wheel failed](https://github.com/prashnts/pybloomfiltermmap3/assets/59926080/ec0e4e28-9a74-4503-9771-aa1b8bf6c7d5)

Collecting pybloomfiltermmap3
  Downloading pybloomfiltermmap3-0.5.7.tar.gz (490 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 490.1/490.1 kB 200.7 kB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: pybloomfiltermmap3
  Building wheel for pybloomfiltermmap3 (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for pybloomfiltermmap3 (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [129 lines of output]
      running bdist_wheel
      running build
      running build_ext
      building 'pybloomfilter' extension
      creating build
      creating build\temp.win-amd64-cpython-312
      creating build\temp.win-amd64-cpython-312\Release
      creating build\temp.win-amd64-cpython-312\Release\src
      "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.34.31933\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -IC:\Users\Rehan43V3R\AppData\Local\Programs\Python\Python312\include -IC:\Users\Rehan43V3R\AppData\Local\Programs\Python\Python312\Include "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.34.31933\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.34.31933\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\VS\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\um" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\shared" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\winrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\cppwinrt" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" /Tcsrc/MurmurHash3.c /Fobuild\temp.win-amd64-cpython-312\Release\src/MurmurHash3.obj
      MurmurHash3.c
      "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.34.31933\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -IC:\Users\Rehan43V3R\AppData\Local\Programs\Python\Python312\include -IC:\Users\Rehan43V3R\AppData\Local\Programs\Python\Python312\Include "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.34.31933\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.34.31933\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\VS\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\um" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\shared" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\winrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\cppwinrt" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" /Tcsrc/bloomfilter.c /Fobuild\temp.win-amd64-cpython-312\Release\src/bloomfilter.obj
      bloomfilter.c
      C:\Users\Rehan43V3R\AppData\Local\Temp\pip-install-ju606zf1\pybloomfiltermmap3_cfaf27b5616f4167bd0690029e95e976\src\mmapbitarray.h(76): error C2143: syntax error: missing ')' before '('
      C:\Users\Rehan43V3R\AppData\Local\Temp\pip-install-ju606zf1\pybloomfiltermmap3_cfaf27b5616f4167bd0690029e95e976\src\mmapbitarray.h(76): error C2059: syntax error: ')'
      C:\Users\Rehan43V3R\AppData\Local\Temp\pip-install-ju606zf1\pybloomfiltermmap3_cfaf27b5616f4167bd0690029e95e976\src\mmapbitarray.h(79): error C2143: syntax error: missing ')' before 'type'
      C:\Users\Rehan43V3R\AppData\Local\Temp\pip-install-ju606zf1\pybloomfiltermmap3_cfaf27b5616f4167bd0690029e95e976\src\mmapbitarray.h(79): error C2091: function returns function
      C:\Users\Rehan43V3R\AppData\Local\Temp\pip-install-ju606zf1\pybloomfiltermmap3_cfaf27b5616f4167bd0690029e95e976\src\mmapbitarray.h(79): error C2085: '_vector_byte': not in formal parameter list
      C:\Users\Rehan43V3R\AppData\Local\Temp\pip-install-ju606zf1\pybloomfiltermmap3_cfaf27b5616f4167bd0690029e95e976\src\mmapbitarray.h(79): error C2143: syntax error: missing ';' before '{'
      C:\Users\Rehan43V3R\AppData\Local\Temp\pip-install-ju606zf1\pybloomfiltermmap3_cfaf27b5616f4167bd0690029e95e976\src\mmapbitarray.h(80): error C2065: 'bit': undeclared identifier
      C:\Users\Rehan43V3R\AppData\Local\Temp\pip-install-ju606zf1\pybloomfiltermmap3_cfaf27b5616f4167bd0690029e95e976\src\mmapbitarray.h(80): warning C4047: 'return': 'int (__cdecl *)()' differs in levels of indirection from 'int'
      C:\Users\Rehan43V3R\AppData\Local\Temp\pip-install-ju606zf1\pybloomfiltermmap3_cfaf27b5616f4167bd0690029e95e976\src\mmapbitarray.h(82): error C2143: syntax error: missing ')' before '('
      C:\Users\Rehan43V3R\AppData\Local\Temp\pip-install-ju606zf1\pybloomfiltermmap3_cfaf27b5616f4167bd0690029e95e976\src\mmapbitarray.h(82): error C2059: syntax error: ')'
      C:\Users\Rehan43V3R\AppData\Local\Temp\pip-install-ju606zf1\pybloomfiltermmap3_cfaf27b5616f4167bd0690029e95e976\src\mmapbitarray.h(85): error C2143: syntax error: missing ')' before 'type'
      C:\Users\Rehan43V3R\AppData\Local\Temp\pip-install-ju606zf1\pybloomfiltermmap3_cfaf27b5616f4167bd0690029e95e976\src\mmapbitarray.h(85): error C2091: function returns function
      C:\Users\Rehan43V3R\AppData\Local\Temp\pip-install-ju606zf1\pybloomfiltermmap3_cfaf27b5616f4167bd0690029e95e976\src\mmapbitarray.h(82): error C2084: function 'int (__cdecl *__attribute__())()' already has a body
      C:\Users\Rehan43V3R\AppData\Local\Temp\pip-install-ju606zf1\pybloomfiltermmap3_cfaf27b5616f4167bd0690029e95e976\src\mmapbitarray.h(76): note: see previous definition of '__attribute__'
      C:\Users\Rehan43V3R\AppData\Local\Temp\pip-install-ju606zf1\pybloomfiltermmap3_cfaf27b5616f4167bd0690029e95e976\src\mmapbitarray.h(86): error C2085: 'mbarray_Set': not in formal parameter list
      C:\Users\Rehan43V3R\AppData\Local\Temp\pip-install-ju606zf1\pybloomfiltermmap3_cfaf27b5616f4167bd0690029e95e976\src\mmapbitarray.h(86): error C2143: syntax error: missing ';' before '{'
      C:\Users\Rehan43V3R\AppData\Local\Temp\pip-install-ju606zf1\pybloomfiltermmap3_cfaf27b5616f4167bd0690029e95e976\src\mmapbitarray.h(87): error C2065: 'bit': undeclared identifier
      C:\Users\Rehan43V3R\AppData\Local\Temp\pip-install-ju606zf1\pybloomfiltermmap3_cfaf27b5616f4167bd0690029e95e976\src\mmapbitarray.h(87): error C2065: 'array': undeclared identifier
      C:\Users\Rehan43V3R\AppData\Local\Temp\pip-install-ju606zf1\pybloomfiltermmap3_cfaf27b5616f4167bd0690029e95e976\src\mmapbitarray.h(87): error C2223: left of '->bits' must point to struct/union
      C:\Users\Rehan43V3R\AppData\Local\Temp\pip-install-ju606zf1\pybloomfiltermmap3_cfaf27b5616f4167bd0690029e95e976\src\mmapbitarray.h(89): warning C4047: 'return': 'int (__cdecl *)()' differs in levels of indirection from 'int'
      C:\Users\Rehan43V3R\AppData\Local\Temp\pip-install-ju606zf1\pybloomfiltermmap3_cfaf27b5616f4167bd0690029e95e976\src\mmapbitarray.h(91): error C2065: 'array': undeclared identifier
      C:\Users\Rehan43V3R\AppData\Local\Temp\pip-install-ju606zf1\pybloomfiltermmap3_cfaf27b5616f4167bd0690029e95e976\src\mmapbitarray.h(91): error C2223: left of '->vector' must point to struct/union
      C:\Users\Rehan43V3R\AppData\Local\Temp\pip-install-ju606zf1\pybloomfiltermmap3_cfaf27b5616f4167bd0690029e95e976\src\mmapbitarray.h(91): warning C4047: 'function': 'MBArray *' differs in levels of indirection from 'int'
      C:\Users\Rehan43V3R\AppData\Local\Temp\pip-install-ju606zf1\pybloomfiltermmap3_cfaf27b5616f4167bd0690029e95e976\src\mmapbitarray.h(91): warning C4024: '_vector_offset': different types for formal and actual parameter 1
      C:\Users\Rehan43V3R\AppData\Local\Temp\pip-install-ju606zf1\pybloomfiltermmap3_cfaf27b5616f4167bd0690029e95e976\src\mmapbitarray.h(91): error C2065: 'bit': undeclared identifier
      C:\Users\Rehan43V3R\AppData\Local\Temp\pip-install-ju606zf1\pybloomfiltermmap3_cfaf27b5616f4167bd0690029e95e976\src\mmapbitarray.h(91): warning C4013: '_vector_byte' undefined; assuming extern returning int
      C:\Users\Rehan43V3R\AppData\Local\Temp\pip-install-ju606zf1\pybloomfiltermmap3_cfaf27b5616f4167bd0690029e95e976\src\mmapbitarray.h(94): error C2143: syntax error: missing ')' before '('
      C:\Users\Rehan43V3R\AppData\Local\Temp\pip-install-ju606zf1\pybloomfiltermmap3_cfaf27b5616f4167bd0690029e95e976\src\mmapbitarray.h(94): error C2059: syntax error: ')'
      C:\Users\Rehan43V3R\AppData\Local\Temp\pip-install-ju606zf1\pybloomfiltermmap3_cfaf27b5616f4167bd0690029e95e976\src\mmapbitarray.h(97): error C2143: syntax error: missing ')' before 'type'
      C:\Users\Rehan43V3R\AppData\Local\Temp\pip-install-ju606zf1\pybloomfiltermmap3_cfaf27b5616f4167bd0690029e95e976\src\mmapbitarray.h(97): error C2091: function returns function
      C:\Users\Rehan43V3R\AppData\Local\Temp\pip-install-ju606zf1\pybloomfiltermmap3_cfaf27b5616f4167bd0690029e95e976\src\mmapbitarray.h(98): error C2085: 'mbarray_Clear': not in formal parameter list
      C:\Users\Rehan43V3R\AppData\Local\Temp\pip-install-ju606zf1\pybloomfiltermmap3_cfaf27b5616f4167bd0690029e95e976\src\mmapbitarray.h(98): error C2143: syntax error: missing ';' before '{'
      C:\Users\Rehan43V3R\AppData\Local\Temp\pip-install-ju606zf1\pybloomfiltermmap3_cfaf27b5616f4167bd0690029e95e976\src\mmapbitarray.h(99): error C2065: 'bit': undeclared identifier
      C:\Users\Rehan43V3R\AppData\Local\Temp\pip-install-ju606zf1\pybloomfiltermmap3_cfaf27b5616f4167bd0690029e95e976\src\mmapbitarray.h(99): error C2065: 'array': undeclared identifier
      C:\Users\Rehan43V3R\AppData\Local\Temp\pip-install-ju606zf1\pybloomfiltermmap3_cfaf27b5616f4167bd0690029e95e976\src\mmapbitarray.h(99): error C2223: left of '->bits' must point to struct/union
      C:\Users\Rehan43V3R\AppData\Local\Temp\pip-install-ju606zf1\pybloomfiltermmap3_cfaf27b5616f4167bd0690029e95e976\src\mmapbitarray.h(101): warning C4047: 'return': 'int (__cdecl *)()' differs in levels of indirection from 'int'
      C:\Users\Rehan43V3R\AppData\Local\Temp\pip-install-ju606zf1\pybloomfiltermmap3_cfaf27b5616f4167bd0690029e95e976\src\mmapbitarray.h(103): error C2065: 'array': undeclared identifier
      C:\Users\Rehan43V3R\AppData\Local\Temp\pip-install-ju606zf1\pybloomfiltermmap3_cfaf27b5616f4167bd0690029e95e976\src\mmapbitarray.h(103): error C2223: left of '->vector' must point to struct/union
      C:\Users\Rehan43V3R\AppData\Local\Temp\pip-install-ju606zf1\pybloomfiltermmap3_cfaf27b5616f4167bd0690029e95e976\src\mmapbitarray.h(103): warning C4047: 'function': 'MBArray *' differs in levels of indirection from 'int'
      C:\Users\Rehan43V3R\AppData\Local\Temp\pip-install-ju606zf1\pybloomfiltermmap3_cfaf27b5616f4167bd0690029e95e976\src\mmapbitarray.h(103): warning C4024: '_vector_offset': different types for formal and actual parameter 1
      C:\Users\Rehan43V3R\AppData\Local\Temp\pip-install-ju606zf1\pybloomfiltermmap3_cfaf27b5616f4167bd0690029e95e976\src\mmapbitarray.h(103): error C2065: 'bit': undeclared identifier
      C:\Users\Rehan43V3R\AppData\Local\Temp\pip-install-ju606zf1\pybloomfiltermmap3_cfaf27b5616f4167bd0690029e95e976\src\mmapbitarray.h(106): error C2143: syntax error: missing ')' before '('
      C:\Users\Rehan43V3R\AppData\Local\Temp\pip-install-ju606zf1\pybloomfiltermmap3_cfaf27b5616f4167bd0690029e95e976\src\mmapbitarray.h(106): error C2059: syntax error: ')'
      C:\Users\Rehan43V3R\AppData\Local\Temp\pip-install-ju606zf1\pybloomfiltermmap3_cfaf27b5616f4167bd0690029e95e976\src\mmapbitarray.h(109): error C2143: syntax error: missing ')' before 'type'
      C:\Users\Rehan43V3R\AppData\Local\Temp\pip-install-ju606zf1\pybloomfiltermmap3_cfaf27b5616f4167bd0690029e95e976\src\mmapbitarray.h(109): error C2091: function returns function
      C:\Users\Rehan43V3R\AppData\Local\Temp\pip-install-ju606zf1\pybloomfiltermmap3_cfaf27b5616f4167bd0690029e95e976\src\mmapbitarray.h(110): error C2085: 'mbarray_Test': not in formal parameter list
      C:\Users\Rehan43V3R\AppData\Local\Temp\pip-install-ju606zf1\pybloomfiltermmap3_cfaf27b5616f4167bd0690029e95e976\src\mmapbitarray.h(110): error C2143: syntax error: missing ';' before '{'
      C:\Users\Rehan43V3R\AppData\Local\Temp\pip-install-ju606zf1\pybloomfiltermmap3_cfaf27b5616f4167bd0690029e95e976\src\mmapbitarray.h(111): error C2065: 'bit': undeclared identifier
      C:\Users\Rehan43V3R\AppData\Local\Temp\pip-install-ju606zf1\pybloomfiltermmap3_cfaf27b5616f4167bd0690029e95e976\src\mmapbitarray.h(111): error C2065: 'array': undeclared identifier
      C:\Users\Rehan43V3R\AppData\Local\Temp\pip-install-ju606zf1\pybloomfiltermmap3_cfaf27b5616f4167bd0690029e95e976\src\mmapbitarray.h(111): error C2223: left of '->bits' must point to struct/union
      C:\Users\Rehan43V3R\AppData\Local\Temp\pip-install-ju606zf1\pybloomfiltermmap3_cfaf27b5616f4167bd0690029e95e976\src\mmapbitarray.h(113): warning C4047: 'return': 'int (__cdecl *)()' differs in levels of indirection from 'int'
      C:\Users\Rehan43V3R\AppData\Local\Temp\pip-install-ju606zf1\pybloomfiltermmap3_cfaf27b5616f4167bd0690029e95e976\src\mmapbitarray.h(115): error C2065: 'array': undeclared identifier
      C:\Users\Rehan43V3R\AppData\Local\Temp\pip-install-ju606zf1\pybloomfiltermmap3_cfaf27b5616f4167bd0690029e95e976\src\mmapbitarray.h(115): error C2223: left of '->vector' must point to struct/union
      C:\Users\Rehan43V3R\AppData\Local\Temp\pip-install-ju606zf1\pybloomfiltermmap3_cfaf27b5616f4167bd0690029e95e976\src\mmapbitarray.h(115): warning C4047: 'function': 'MBArray *' differs in levels of indirection from 'int'
      C:\Users\Rehan43V3R\AppData\Local\Temp\pip-install-ju606zf1\pybloomfiltermmap3_cfaf27b5616f4167bd0690029e95e976\src\mmapbitarray.h(115): warning C4024: '_vector_offset': different types for formal and actual parameter 1
      C:\Users\Rehan43V3R\AppData\Local\Temp\pip-install-ju606zf1\pybloomfiltermmap3_cfaf27b5616f4167bd0690029e95e976\src\mmapbitarray.h(115): error C2065: 'bit': undeclared identifier
      C:\Users\Rehan43V3R\AppData\Local\Temp\pip-install-ju606zf1\pybloomfiltermmap3_cfaf27b5616f4167bd0690029e95e976\src\mmapbitarray.h(115): warning C4033: '__attribute__' must return a value
      C:\Users\Rehan43V3R\AppData\Local\Temp\pip-install-ju606zf1\pybloomfiltermmap3_cfaf27b5616f4167bd0690029e95e976\src\mmapbitarray.h(117): error C2143: syntax error: missing ')' before '('
      C:\Users\Rehan43V3R\AppData\Local\Temp\pip-install-ju606zf1\pybloomfiltermmap3_cfaf27b5616f4167bd0690029e95e976\src\mmapbitarray.h(117): error C2059: syntax error: ')'
      C:\Users\Rehan43V3R\AppData\Local\Temp\pip-install-ju606zf1\pybloomfiltermmap3_cfaf27b5616f4167bd0690029e95e976\src\bloomfilter.h(9): error C2143: syntax error: missing ')' before '<class-head>'
      C:\Users\Rehan43V3R\AppData\Local\Temp\pip-install-ju606zf1\pybloomfiltermmap3_cfaf27b5616f4167bd0690029e95e976\src\bloomfilter.h(9): error C2091: function returns function
      C:\Users\Rehan43V3R\AppData\Local\Temp\pip-install-ju606zf1\pybloomfiltermmap3_cfaf27b5616f4167bd0690029e95e976\src\bloomfilter.h(25): error C2085: 'Key': not in formal parameter list
      C:\Users\Rehan43V3R\AppData\Local\Temp\pip-install-ju606zf1\pybloomfiltermmap3_cfaf27b5616f4167bd0690029e95e976\src\bloomfilter.h(27): error C2085: 'BloomFilter': not in formal parameter list
      C:\Users\Rehan43V3R\AppData\Local\Temp\pip-install-ju606zf1\pybloomfiltermmap3_cfaf27b5616f4167bd0690029e95e976\src\bloomfilter.h(30): error C2061: syntax error: identifier 'BloomFilter'
      C:\Users\Rehan43V3R\AppData\Local\Temp\pip-install-ju606zf1\pybloomfiltermmap3_cfaf27b5616f4167bd0690029e95e976\src\bloomfilter.h(34): error C2143: syntax error: missing '{' before '*'
      C:\Users\Rehan43V3R\AppData\Local\Temp\pip-install-ju606zf1\pybloomfiltermmap3_cfaf27b5616f4167bd0690029e95e976\src\bloomfilter.h(38): error C2143: syntax error: missing ')' before '*'
      C:\Users\Rehan43V3R\AppData\Local\Temp\pip-install-ju606zf1\pybloomfiltermmap3_cfaf27b5616f4167bd0690029e95e976\src\bloomfilter.h(38): error C2143: syntax error: missing '{' before '*'
      C:\Users\Rehan43V3R\AppData\Local\Temp\pip-install-ju606zf1\pybloomfiltermmap3_cfaf27b5616f4167bd0690029e95e976\src\bloomfilter.h(38): error C2059: syntax error: ')'
      C:\Users\Rehan43V3R\AppData\Local\Temp\pip-install-ju606zf1\pybloomfiltermmap3_cfaf27b5616f4167bd0690029e95e976\src\bloomfilter.h(39): error C2143: syntax error: missing ')' before '*'
      C:\Users\Rehan43V3R\AppData\Local\Temp\pip-install-ju606zf1\pybloomfiltermmap3_cfaf27b5616f4167bd0690029e95e976\src\bloomfilter.h(39): error C2143: syntax error: missing '{' before '*'
      C:\Users\Rehan43V3R\AppData\Local\Temp\pip-install-ju606zf1\pybloomfiltermmap3_cfaf27b5616f4167bd0690029e95e976\src\bloomfilter.h(39): error C2059: syntax error: 'type'
      C:\Users\Rehan43V3R\AppData\Local\Temp\pip-install-ju606zf1\pybloomfiltermmap3_cfaf27b5616f4167bd0690029e95e976\src\bloomfilter.h(39): error C2059: syntax error: ')'
      C:\Users\Rehan43V3R\AppData\Local\Temp\pip-install-ju606zf1\pybloomfiltermmap3_cfaf27b5616f4167bd0690029e95e976\src\bloomfilter.h(40): error C2143: syntax error: missing ')' before '*'
      C:\Users\Rehan43V3R\AppData\Local\Temp\pip-install-ju606zf1\pybloomfiltermmap3_cfaf27b5616f4167bd0690029e95e976\src\bloomfilter.h(40): error C2143: syntax error: missing '{' before '*'
      C:\Users\Rehan43V3R\AppData\Local\Temp\pip-install-ju606zf1\pybloomfiltermmap3_cfaf27b5616f4167bd0690029e95e976\src\bloomfilter.h(40): error C2059: syntax error: ')'
      C:\Users\Rehan43V3R\AppData\Local\Temp\pip-install-ju606zf1\pybloomfiltermmap3_cfaf27b5616f4167bd0690029e95e976\src\bloomfilter.h(42): error C2143: syntax error: missing '{' before '*'
      C:\Users\Rehan43V3R\AppData\Local\Temp\pip-install-ju606zf1\pybloomfiltermmap3_cfaf27b5616f4167bd0690029e95e976\src\bloomfilter.h(42): error C2143: syntax error: missing ')' before '*'
      C:\Users\Rehan43V3R\AppData\Local\Temp\pip-install-ju606zf1\pybloomfiltermmap3_cfaf27b5616f4167bd0690029e95e976\src\bloomfilter.h(42): error C2059: syntax error: 'type'
      C:\Users\Rehan43V3R\AppData\Local\Temp\pip-install-ju606zf1\pybloomfiltermmap3_cfaf27b5616f4167bd0690029e95e976\src\bloomfilter.h(42): error C2059: syntax error: ')'
      C:\Users\Rehan43V3R\AppData\Local\Temp\pip-install-ju606zf1\pybloomfiltermmap3_cfaf27b5616f4167bd0690029e95e976\src\bloomfilter.h(45): error C2143: syntax error: missing ')' before '*'
      C:\Users\Rehan43V3R\AppData\Local\Temp\pip-install-ju606zf1\pybloomfiltermmap3_cfaf27b5616f4167bd0690029e95e976\src\bloomfilter.h(45): error C2081: 'Key': name in formal parameter list illegal
      C:\Users\Rehan43V3R\AppData\Local\Temp\pip-install-ju606zf1\pybloomfiltermmap3_cfaf27b5616f4167bd0690029e95e976\src\bloomfilter.h(45): error C2143: syntax error: missing '{' before '*'
      C:\Users\Rehan43V3R\AppData\Local\Temp\pip-install-ju606zf1\pybloomfiltermmap3_cfaf27b5616f4167bd0690029e95e976\src\bloomfilter.h(45): error C2059: syntax error: ')'
      C:\Users\Rehan43V3R\AppData\Local\Temp\pip-install-ju606zf1\pybloomfiltermmap3_cfaf27b5616f4167bd0690029e95e976\src\bloomfilter.h(47): error C2143: syntax error: missing ')' before '*'
      C:\Users\Rehan43V3R\AppData\Local\Temp\pip-install-ju606zf1\pybloomfiltermmap3_cfaf27b5616f4167bd0690029e95e976\src\bloomfilter.h(47): error C2081: 'Key': name in formal parameter list illegal
      C:\Users\Rehan43V3R\AppData\Local\Temp\pip-install-ju606zf1\pybloomfiltermmap3_cfaf27b5616f4167bd0690029e95e976\src\bloomfilter.h(47): error C2143: syntax error: missing '{' before '*'
      C:\Users\Rehan43V3R\AppData\Local\Temp\pip-install-ju606zf1\pybloomfiltermmap3_cfaf27b5616f4167bd0690029e95e976\src\bloomfilter.h(47): error C2059: syntax error: ')'
      C:\Users\Rehan43V3R\AppData\Local\Temp\pip-install-ju606zf1\pybloomfiltermmap3_cfaf27b5616f4167bd0690029e95e976\src\bloomfilter.h(50): error C2143: syntax error: missing ')' before '*'
      C:\Users\Rehan43V3R\AppData\Local\Temp\pip-install-ju606zf1\pybloomfiltermmap3_cfaf27b5616f4167bd0690029e95e976\src\bloomfilter.h(50): error C2143: syntax error: missing '{' before '*'
      C:\Users\Rehan43V3R\AppData\Local\Temp\pip-install-ju606zf1\pybloomfiltermmap3_cfaf27b5616f4167bd0690029e95e976\src\bloomfilter.h(50): error C2143: syntax error: missing ';' before '*'
      C:\Users\Rehan43V3R\AppData\Local\Temp\pip-install-ju606zf1\pybloomfiltermmap3_cfaf27b5616f4167bd0690029e95e976\src\bloomfilter.h(50): error C2059: syntax error: ')'
      C:\Users\Rehan43V3R\AppData\Local\Temp\pip-install-ju606zf1\pybloomfiltermmap3_cfaf27b5616f4167bd0690029e95e976\src\bloomfilter.h(51): error C2054: expected '(' to follow 'key'
      C:\Users\Rehan43V3R\AppData\Local\Temp\pip-install-ju606zf1\pybloomfiltermmap3_cfaf27b5616f4167bd0690029e95e976\src\bloomfilter.h(75): error C2143: syntax error: missing ')' before '('
      C:\Users\Rehan43V3R\AppData\Local\Temp\pip-install-ju606zf1\pybloomfiltermmap3_cfaf27b5616f4167bd0690029e95e976\src\bloomfilter.h(75): error C2059: syntax error: ')'
      C:\Users\Rehan43V3R\AppData\Local\Temp\pip-install-ju606zf1\pybloomfiltermmap3_cfaf27b5616f4167bd0690029e95e976\src\bloomfilter.h(78): error C2143: syntax error: missing ')' before 'type'
      C:\Users\Rehan43V3R\AppData\Local\Temp\pip-install-ju606zf1\pybloomfiltermmap3_cfaf27b5616f4167bd0690029e95e976\src\bloomfilter.h(78): error C2091: function returns function
      C:\Users\Rehan43V3R\AppData\Local\Temp\pip-install-ju606zf1\pybloomfiltermmap3_cfaf27b5616f4167bd0690029e95e976\src\bloomfilter.h(78): error C2143: syntax error: missing ')' before '*'
      C:\Users\Rehan43V3R\AppData\Local\Temp\pip-install-ju606zf1\pybloomfiltermmap3_cfaf27b5616f4167bd0690029e95e976\src\bloomfilter.h(78): error C2085: 'bloomfilter_Test': not in formal parameter list
      C:\Users\Rehan43V3R\AppData\Local\Temp\pip-install-ju606zf1\pybloomfiltermmap3_cfaf27b5616f4167bd0690029e95e976\src\bloomfilter.h(78): error C2143: syntax error: missing ';' before '*'
      C:\Users\Rehan43V3R\AppData\Local\Temp\pip-install-ju606zf1\pybloomfiltermmap3_cfaf27b5616f4167bd0690029e95e976\src\bloomfilter.h(78): error C2059: syntax error: ')'
      C:\Users\Rehan43V3R\AppData\Local\Temp\pip-install-ju606zf1\pybloomfiltermmap3_cfaf27b5616f4167bd0690029e95e976\src\bloomfilter.h(94): error C2143: syntax error: missing ')' before '('
      C:\Users\Rehan43V3R\AppData\Local\Temp\pip-install-ju606zf1\pybloomfiltermmap3_cfaf27b5616f4167bd0690029e95e976\src\bloomfilter.h(94): error C2059: syntax error: ')'
      src/bloomfilter.c(11): error C2146: syntax error: missing ')' before identifier 'BloomFilter'
      src/bloomfilter.c(11): error C2091: function returns function
      src/bloomfilter.c(11): error C2061: syntax error: identifier 'BloomFilter'
      src/bloomfilter.c(11): error C2059: syntax error: ';'
      src/bloomfilter.c(14): error C2065: 'BloomFilter': undeclared identifier
      src/bloomfilter.c(14): error C2065: 'bf': undeclared identifier
      src/bloomfilter.c(14): error C2059: syntax error: ')'
      src/bloomfilter.c(17): error C2065: 'bf': undeclared identifier
      src/bloomfilter.c(21): error C2065: 'bf': undeclared identifier
      src/bloomfilter.c(21): warning C4022: 'memset': pointer mismatch for actual parameter 1
      src/bloomfilter.c(21): error C2065: 'BloomFilter': undeclared identifier
      src/bloomfilter.c(23): error C2065: 'bf': undeclared identifier
      src/bloomfilter.c(23): error C2223: left of '->max_num_elem' must point to struct/union
      src/bloomfilter.c(23): fatal error C1003: error count exceeds 100; stopping compilation
      error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.34.31933\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pybloomfiltermmap3
Failed to build pybloomfiltermmap3
ERROR: Could not build wheels for pybloomfiltermmap3, which is required to install pyproject.toml-based projects

**Comment by prashnts** [comment]
Windows is not supported, sorry.
